### ISSUE TITLE
Property mapping should handle multiple mappings

### ISSUE THREAD

**Issue by ccondit** [SciGraph/SciGraph#111]
When mapping properties during loading many to many mappings should be supported.
For instance:

```
mappedProperties:
 - name: label # The name of the new property
   properties: # The list of properties mapped to the new property
   - http://www.w3.org/2000/01/rdf-schema#label
   - http://www.w3.org/2004/02/skos/core#prefLabel
 - name: synonym
   properties:
   - http://purl.obolibrary.org/obo#Synonym
   - http://www.w3.org/2004/02/skos/core#prefLabel
```

`prefLabel` should map to both label and synonym. Currently it only maps to the last entry found.
