### ISSUE TITLE
SciDump: Create a JSON dumping framework that can be used for Solr loading

### ISSUE THREAD

**Issue by cmungall** [SciGraph/SciGraph#46]
## Overview and Requirements

We need a means of generating custom JSON exports of portions of a
SciGraph database. The primary use case here is as a mechanism for
providing Solr views (or Elastic Search?) over SG data, but the
feature could also have other uses.

Formally, this is the same as extraction of a subgraph, followed by an
optional transformation step that performs any necessary flattening.

The challenge here is that we will likely want a number of different
such views, so the mechanism for specifying the extraction/mapping
*must* be reasonably declarative. 

Another requirement is that the transformation may optionally make use
of a reasoner to calculate inferred paths and materialize these in the
exported structure. 

A requirement that can be implemented later is schema checking on the
resulting extracted JSON. We would like all mapping specifications
should be checked as close to authoring time as possible. For the
dump-to-solr usecase, we already have a yaml configuration specified
(@kltm - can you provide a link to the docs).

## Mapping specification language

We will avoid creating Yet Another Ad-Hoc custom configuration format.

One option would be to specify this with something like SPARQL
CONSTRUCT, or the equivalent in Cypher, but in my experience the more
granular control offered by a programming language is often
necessary. However, a hybrid Cypher/code model would be possible.

My top candidate here would be to specify the mapping in a programming
language that is declarative and JSON-ready: javascript running on the
JVM (Narwhal, Rhino or Ringo) is a natural choice, but arguments could
be made for Scala, Groovy or Jython. Pure java code is probably too
verbose. JVM is probably a requirement, to be able to directly access
API calls (either SG, Neo, OWLAPI, Jena or whatever).

## Storing ancestry information

We will want to allow the optional expansion of some objects to
include all ancestors. Here by ancestors we mean both superclasses,
and ancestors of the form "R some Y".

In many cases we will need to do this using the OWLAPI Reasoner API,
which would require the necessary ontologies to be in memory.

The ExpressionMaterializingReasoner from owltools should be
modularized and used here (cc @hdietze).

We may want to treat this as a separate concern: have the dumper be
one component, and then as a post-processing step enhance certain
objects in the JSON via reasoning.

## Example

Much of our data follows a common pattern: a typed association between
a biological entity and something else, typically an ontology class;
here the association typically is adorned with evidence, provenance
etc info.

We will take disease-phenotype associations as our canonical example.

The desired output follows a typical Golr pattern, where objects are
flattened to {id,label} pairs, and ancestors are flattened two an ID
list and label list.

(This example will likely be tweaked after discussion with @ktlm)

```
{
 document_type: "DiseasePhenotypeAssociation",

 bioentity_id: "OMIM:1234",
 bioentity_label: "Foo disease",

 annotation_class_id: "HP:9876",
 annotation_class_label: "big ears",
 annotation_class_closure: ["HP:9876", ...ANCESTORS],
 annotation_class_label_closure: ["big ears", ...]
 annotation_class_map: {...},

 evidence_id: "ECO:...",
 evidence_label: "author statement",

 publication_id: "PMID:654322",
 publication_label: "the role of big ears in foo disease",

 ...
 
}
```

This structure can trvially be loaded into Solr.

It can also be trivially turned into a CSV or Excel file, which will
be a very useful feature for biologists who want to extract some
custom subset of the data.

### Example mapping

Here we assume that each mapping is specified in a file that is evaluated in js.

Details may not be correct, this is just to give a flavor of how this
might work, TBD. It's not as declarative as I would like.

```
## phenotype-golr.js

function initialize(sg, storeFunc, errFunc) {
  this.scigraph = sg;
  this.name = "phenotype";   ## for introspection
}

function exportAll(cb) {
   ## this part could be replaced by a Cypher query?
   this.sg.getAllObjectsOfType(vocab.Phenotype).forEach(
     function(node) { this.exportPhenotype(node} );
}

function exportPhenotype(node) {

   node.getRelationships(vocab.has_phenotype, Direction.INCOMING).forEach(
     function(rel) { this.exportRelationship(node} );
   );

}

function exportRelationship(rel) {

   this.storeFunc({
      bioentity_id : rel.getSource().getId(),
      bioentity_label : rel.getSource().getProperty(Vocab.label);,
      ....
   });


}

```

**Comment by ccondit** [comment]
SciGraph will support the following conventions:
Given a Cypher query Q with projection P for the subgraph G provide a result processor that produces JSON for GOLR to ingest. This processor will provide the following:

* For every field F in P
  - If F is a primitive then pass through directly to the JSON
  - If F is a node then pass through a "GOLR quad". (CURIE, CURIE closure, label, label closure)
* To produce "evidence" do the following:
  - Add all associations to G
  - Add G'  to the JSON as a serialized JSON blob (graphson or bbop js)
  - Add (G' - node fields in F) to the JSON as a GOLR quad.

The closures for the GOLR quads will subClassOf as a default. An alternate relationship can be supplied by appending `$relationshipName` to F (ie brainRegion$hasPart) in the Cypher query

cc @nlwashington

**Comment by ccondit** [comment]
Here's the mapping file that I'm using to produce the Solr schema:

```
id: annotation
schema_generating: true
description: Associations following OBAN model
display_name: Annotations
document_category: annotation
weight: 20
boost_weights: annotation_class^2.0 annotation_class_label^1.0 bioentity^2.0 bioentity_label^1.0 bioentity_name^1.0 annotation_extension_class^2.0 annotation_extension_class_label^1.0 reference^1.0 panther_family^1.0 panther_family_label^1.0 bioentity_isoform^1.0 regulates_closure^1.0 regulates_closure_label^1.0
result_weights: bioentity^7.0 bioentity_name^6.0 qualifier^5.0 annotation_class^4.7 annotation_extension_json^4.5 source^4.0 taxon^3.0 evidence_type^2.5 evidence_with^2.0 panther_family^1.5 bioentity_isoform^0.5 reference^0.25
filter_weights: source^7.0 assigned_by^6.5 aspect^6.25 evidence_type_closure^6.0 panther_family_label^5.5 qualifier^5.25 taxon_closure_label^5.0 annotation_class_label^4.5 regulates_closure_label^3.0 annotation_extension_class_closure_label^2.0
fields:

  ## SUBJECT

  - id: subject
    description: "The CURIE for oban:association_has_subject. May be disease, variant, gene, person, ...."
    display_name: Assoc subject
    type: string
    property: []

  - id: subject_label
    description: "Label for subject_id. This will always be rdfs:label. Conventions may vary as to what goes in the label. For genes will be symbol, but we may choose to uniquify by prefixing with species"
    display_name: Assoc subject
    type: string
    property: []
    searchable: true

  - id: subject_closure
    description: "Reflexive closure of association_has_subject. A list of CURIEs. If an individual, first traverse rdf:tpye. The default closure is subclass, but other may optionally be added depending on what type of association this is and what the class is. E.g. for expression associations, the object is an anatomy class, and the closure will include part_of"
    display_name: Inferred subject
    type: string
    cardinality: multi
    property: []

  - id: subject_closure_label
    description: "Labels for subject_closure."
    display_name: Involved in
    type: string
    cardinality: multi
    property: []
    searchable: true

  ## OBJECT

  - id: object
    description: "The CURIE for oban:association_has_object. This is often, but not always an ontology class. E.g. for a gene-gene interaction it is an (arbitrary) member of the pair."
    display_name: Assoc object
    type: string
    property: []

  - id: object_label
    description: "Label for object_id."
    display_name: Assoc object
    type: string
    property: []
    searchable: true

  - id: object_closure
    description: "Reflexive closure of association_has_object. A list of CURIEs. If an individual, first traverse rdf:tpye. The default closure is subclass, but other may optionally be added depending on what type of association this is and what the class is. E.g. for expression associations, the object is an anatomy class, and the closure will include part_of"
    display_name: Inferred object
    type: string
    cardinality: multi
    property: []

  - id: object_closure_label
    description: "Labels for object_class_closure."
    display_name: Involved in
    type: string
    cardinality: multi
    property: []
    searchable: true

  ## EVIDENCE

  - id: evidence_graph
    description: "Evidence graph"
    display_name: Evidence graph
    type: string
    property: []

  - id: evidence
    description: "Evidence type. In Monarch we may have a graph/chain. This is always the 'outer' evidence OR a list of all evidence types used?"
    display_name: Evidence type
    type: string
    cardinality: multi
    property: []

  - id: evidence_label
    description: "Closure for evidence_type. Always SubClassof"
    display_name: Evidence label
    type: string
    cardinality: multi
    property: []

  - id: evidence_closure
    description: "List of CURIES of all entities that form part of the evidence graph."
    display_name: Evidence closure
    type: string
    cardinality: multi
    property: []

  - id: evidence_closure_label
    description: "List of CURIES of all entities that form part of the evidence graph."
    display_name: Evidence label closure
    type: string
    cardinality: multi
    property: []
```

Can we adjust this so that it will work with whatever widgets are required?
